# yaml-language-server: $schema=schema/xec-yaml-schema.json
# yaml-language-server: $schema=https://raw.githubusercontent.com/leventogut/xec/main/schema/xec-yaml-schema.json
#imports:
#  - examples/restart-on-failure.xec.yaml
#  - examples/parallel.xec.yaml
verbose: false
debug: false
dev: true
logDir: ./log
logFile: "auto" # "xec.log"
restartLimit: 100
taskDefaults:
  environment:
    passOn: true
  #  logFile: "xec-taskDefaults.log"
  ignoreError: false
tasks:
  - alias: build
    description: Build xec.
    cmd: goreleaser release --snapshot --clean
  - alias: run
    description: go run xec.
    cmd: go run main.go
  - alias: echo_5
    cmd: echo "5"
  - alias: wait_1
    cmd: sleep "1"
    restartOnSuccess: false
  #    logFile: "xec-task.log"
  - alias: wait_3
    cmd: sleep "3"
  - alias: wait_60
    cmd: sleep "60"
  - alias: ls
    cmd: ls -al
    restartOnFailure: false
  - alias: lsz
    cmd: ls "-alz"
    restartOnFailure: false
taskLists:
  - alias: wait
    parallel: false
    taskAliases:
      - wait_1
      - wait_3
    logFile: "parallel.log"
