verbose: true
debug: true
logFile: "xec.log"
environment:
  values:
    - key=value
    - environment=dev
  passOn: true
  acceptFilterRegex:
    - "XEC_*"
  rejectFilterRegex:
    - "*SECRET*"
tasks:
  - alias: printenv
    description: execute printenv, usuallu for debugging.
    cmd: printenv
    wait: true # false will cause xec spawn another process
    retry: 3
  - alias: myls
    description: list files in this directory
    cmd: ls
    args:
      - '-al'
      - '/' # '${DIRECTORY}'
    labels:
      - tools
    tags:
      instance: test
      tool: ls
    environment:
      values:
        - key=value
        - environment=dev
    pass_our_environment: true
    acceptFilterRegex:
      - "XEC_*"
    rejectFilterRegex:
      - "*SECRET*"
    debug: true
    logFile: "myls.log"
  - alias: link-aws
    link: ~/dev/tasks/aws/aws.sh
  - context: ltasks # Local tasks # usage $0 <context_name> <EXECUTABLE_NAME>
    link: ~/dev/tasks/*