# yaml-language-server: $schema=schema/xec-yaml-schema.json
# # yaml-language-server: $schema=https://raw.githubusercontent.com/leventogut/xec/main/schema/xec-yaml-schema.json
taskDefaults:
  logFile: "xec.log"
  environment:
    passOn: true
  ignoreError: false
tasks:
  - alias: build
    description: Build xec.
    cmd: goreleaser
    args:
      - release
      - --snapshot
      - --clean
