# yaml-language-server: $schema=schema/xec-yaml-schema.json
# # yaml-language-server: $schema=https://raw.githubusercontent.com/leventogut/xec/main/schema/xec-yaml-schema.json
#imports:
#  - examples/restart-on-failure.xec.yaml
#  - examples/parallel.xec.yaml
verbose: true
debug: true
logDir: ./log
logFile: "auto" # "xec.log"
taskDefaults:
  environment:
    passOn: true
#  logFile: "xec-taskDefaults.log"
  ignoreError: false
tasks:
  - alias: build
    description: Build xec.
    cmd: goreleaser
    args:
      - release
      - --snapshot
      - --clean
  - alias: echo_5
    cmd: echo
    args:
      - "5"
  - alias: wait_1
    cmd: sleep
    args:
      - "1"
#    logFile: "xec-task.log"
  - alias: wait_3
    cmd: sleep
    args:
      - "3"
  - alias: wait_12
    cmd: sleep
    args:
      - "1"
taskLists:
  - alias: wait
    parallel: false
    taskAliases:
      - wait_1
      - wait_3
#    logFile: "parallel.log"
